version: '3.8'
services:
  db:
    image: postgres:15
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2024      
      - POSTGRES_DB=postgres
    restart: always             # correr como un servicio
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo17:
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "10001:8069"
      - "20001:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo16@2024
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # Paquetes adicionales Python
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # correr como un servicio
    
